### ISSUE TITLE
Draft saved despite being erased

### ISSUE THREAD

**Issue by Cwpute** [FossifyOrg/Messages#13]
**Checklist**
 - [x] I can reproduce the bug with the latest version. 
 - [x] I made sure that there are no existing issues - open or closed - to which I could contribute my information to.
 - [x]  I have read the FAQ and my problem isn't listed.
 - [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
 - [x]  This issue contains only one bug.
 - [x]  I have read and understood the [contribution guidelines.](https://github.com/FossifyOrg/General-Discussion?tab=readme-ov-file#faq)

**Describe the bug**
I have one conversation in which the previous draft keeps being saved. Let's say the draft read `hello`, i enter the conversation, erase the text in the text area, leave the conversation… the draft still

**To Reproduce**
1. Enter a conversation page
2. Write some text in the text area: eg. `hello`
3. Leave the conversation
4. Draft is saved as expected, shown to be `hello`
5. Enter the conversation again
6. Change draft to any other text, a single letter is enough: eg `E`
7. Leave conversation
8. Draft is changed and saved as expected, and is shown to be `E`
9. Enter conversation again
10. Erase entirely previous draft `E` from the text area
11. Leave conversation
12. *Draft isn't erased* and is shown to still be `E`

**Expected behavior**
Draft should be erased and forgotten about after being deleted from the text area

**Device info (please complete the following information):**
 - Model: NOKIA TA-1157
 - OS: Android 11
 - Version: SMT 5.19.3

**Additional context**
i checked on SMT issue tracker and haven't seen issues about this.

**Comment by Aga-C** [comment]
I've checked it on three different phones, with different Android versions, and I couldn't reproduce it, so I set this bug as device specific.

If someone else also encountered this issue, please let us know what device and OS are you using.

**Comment by Cwpute** [comment]
Yeah it seems strange here too because the bug seemingly happened out of nowhere, i had drafts before on the same app version but this has never happened.

I suspected this had something to do with the specific conversation it happened in first, but i don't know why. The main difference from other conversations i can think of is that i sent a lot of MMS in the past and still do.
But i tried with several other conversations after that and i can reproduce it 🤔

Maybe something to do with my keyboard ? i use AnysoftKeyboard, and have also installed ThumbKey, which i don't use. I'll have a look into it.

Le 28 décembre 2023 12:21:52 GMT+01:00, Agnieszka C ***@***.***> a écrit :

**Comment by Chaman-veteran** [comment]
> vice and O

I have the same issue on Pixel 6A Android 14 (using SMT 5.19.3) but it seems pretty random.
So far it only happened for 2 discussions for me, and uninstall/clear cache doesn't work.
I'm using FlorisBoard keyboard so it doesn't seems to be linked to the keyboard we use...

**Comment by PrivacyFriendlyMuffins** [comment]
Same thing is happening to me, but only on 1 contact.

Device: Motorola One 5g Ace
OS: Android 11

I use OpenBoard.

**Comment by PrivacyFriendlyMuffins** [comment]
So, I know this is open-source, so I'm trying my best to be patient, but I just thought I'd ask if there is any progress on fixing this. :)

**Comment by DeclanChidlow** [comment]
I would like to add that I encounter this bug as well.
I'm using a Nokia G22 with Android 13. I downloaded Fossify from F-Droid using NeoStore my keyboard of choice is FlorisBoard.

No other apps exhibit this behavior. Let me know if there is any further information I can provide.

**Comment by anaskaejdar** [comment]
What if there was a “clear all drafts” button somewhere? Even if this wasn't a problem, it would be good to have that.

And then, imagine!: In the long term, that feature could expand into a separate page or tab which would list all saved drafts, just like a traditional email client. And there could be another tab-or-page which would list scheduled messages that haven't been sent yet.

All that is to say that even though for the problem at hand, it's mere bandagework, this would be a good move, which would even pave the way for some nice extra UX improvements later. And it would be vely effective bandagework.

**Comment by anaskaejdar** [comment]
by the way, I soticod that it's more likely to create a problem if you write a message, switch focus to a different app, and then come back. Switching focus causes a draft to be saved. But it seems like the draft can never be overwritten by as empty string, so if you erase everything and try the same routine, the old message comes back.

**Comment by Cwpute** [comment]
Agreed.
An option to "clear all drafts" would at least alleviate the issue and provide us with some way to circumvent the problem until it is solved.

Le 24 février 2024 21:01:55 GMT+01:00, "Anastázius Kaejatídarján" ***@***.***> a écrit :

**Comment by TesterEU** [comment]
This basic functionality hasn't been fixed yet?! People are reporting this error on the internet (App ratings are getting lower):
1. https://liliputing.com/fossify-apps-pick-up-where-simple-mobile-tools-left-off-free-and-open-source-suite-of-android-apps/
2. https://play.google.com/store/apps/details?id=org.fossify.messages
I've the same problem LG V30 Android version 9 kernel 4.4 (system default keyboard).
Will this error be taken seriously?

**Comment by DeclanChidlow** [comment]
> This basic functionality hasn't been fixed yet?! People are reporting this error on the internet (App ratings are getting lower):
> 
>     1. https://liliputing.com/fossify-apps-pick-up-where-simple-mobile-tools-left-off-free-and-open-source-suite-of-android-apps/
> 
>     2. https://play.google.com/store/apps/details?id=org.fossify.messages
>        I've the same problem LG V30 Android version 9 kernel 4.4 (system default keyboard).
>        Will this error be taken seriously?

Tone down the passive aggressive tone. This is a FOSS project being undertaken by volunteers. Hostility leads nowhere.

**Comment by TesterEU** [comment]
> Tone down the passive aggressive tone. This is a FOSS project being undertaken by volunteers. Hostility leads nowhere.

Absolutely not. My tone isn't aggressive. I was alerted to the seriousness of the problem.
**I'm sorry if I offended anyone.**
I appreciate the work of volunteers and the fact that open code makes the world better and safer. This makes everyone we know a tester of this application. If the basic functionality doesn't work, people think **badly** about open source. The problem here is the basic functionality (editing messages) -> draft. Many organizations would choose not to release an application with such a bug or would treat the bug as a top priority.

Back to the topic.
**Is anyone working on fixing this bug?**

**Comment by DeclanChidlow** [comment]
Cheers for the response. Apologies if I was a tad snappy.

It seems it's on their radar as evidenced by the help wanted tag, but not yet in progress. Likely due to troubles reproducing it.

I encounter it on one of my devices so I may see what I can do when I have time. Saying that, it may be a bit off given my current schedule.

**Comment by Aga-C** [comment]
@TesterEU We are aware of that issue, that's why it's ready for development (no `needs triage` label), and we've even labeled it as `help wanted` to show potential contributors that we'd like help here. There's a lot of work with releasing and maintaining all the apps and none of us do it full-time, please be patient.

**Comment by RobyB89** [comment]
> Cheers for the response. Apologies if I was a tad snappy.
> 
> It seems it's on their radar as evidenced by the help wanted tag, but not yet in progress. Likely due to troubles reproducing it.
> 
> I encounter it on one of my devices so I may see what I can do when I have time. Saying that, it may be a bit off given my current schedule.

Thank you for your commitment to solving the problem. I believe that it is worth being an active user -> reporting, paying attention. A passive user will not help in the development of opensource applications.

**Comment by TesterEU** [comment]
> Cheers for the response. Apologies if I was a tad snappy.

no problem. I'm glad I was understood.

@RobyB89 
I've the same opinion

@Aga-C 
I understand and hope the error will be fixed soon. I believe the bug reported is serious. Thank you and everyone involved.

**Comment by jahway603** [comment]
I'm using version 1.0.1 (which was released after this Issue was opened) on Android 14 & I am encountering a similar issue with the exception of Step 12 in the OP - after I delete `E`, there is no draft saved but that message pops up to the top of all the messages, as if it were sent on April 10th, 2024, but it last had conversation within it during January 2024, so I would expect it to return back in the order it was before attemping a drafted message.

**Comment by Pi-iP** [comment]
Hey there,
For information, I am facing the described bug too, with this configuration:

- Fossify app version = 1.0.1  (downloaded from F-droid)
- OS version             = Android 14
- Phone model         = Sony Xperia 10 IV (Model XQ-CC54)

Hoping this problem will finally be solved,

Big thank to all of the team of volunteers working for the community ;) !

**Comment by ZicPL** [comment]
I read this thread because I had a similar problem. As I see, problem is **not solved** to this day.
All the commenters above didn't want to blame You (and devs). I also don't want to be rude and I want to write that I really appreciate Your work. I'm grateful for Your hard work and participation in FOSS. I've been using a similar application since yesterday:
[octoshrimpy/quik](https://github.com/octoshrimpy/quik)
I'm testing the new app from the link above and so far I haven't had a problem with erased Draft saved messages. Maybe the application code from the link will help you solve the problem reported here. If my message is helpful, please let me know here :)

**Comment by botus99** [comment]
Tossing my name in the hat here, hi all. I have been experiencing this error for a while now. Here is my current info...

- Fossify app version = 1.0.1 (downloaded from F-droid)
- OS version = Android 12
- Phone model = Samsung Galaxy Note10+ 5G (Model SM-N976U)

Hope this info helps someone and thanks for the hard work!

**Comment by tylerpalcic** [comment]
I've also been seeing this issue for a few months now.

- Fossify app version = 1.0.1 (downloaded from F-droid)
- OS version = Android 14
- Phone model = ThinkPhone by motorola

**Comment by TereyagiTR** [comment]
@ZicPL  Thank You !! For sending the open alternative 👍 

My Sony Xperia Pro has the draft message problem too. 
Is anyone maintaining this application? She seems dead..

**Comment by naveensingh** [comment]
All Fossify apps are being maintained, just not at the pace I would like to.

**Comment by DeclanChidlow** [comment]
> All Fossify apps are being maintained, just not at the pace I would like to.

You're doing a stellar job. Thanks for the effort!

**Comment by TereyagiTR** [comment]
> All Fossify apps are being maintained, just not at the pace I would like to.

My observation wasn't accurate. I was pleased to hear that the project hasn't been abandoned. I'm currently reviewing it and hope to use your app again in the future. I would be interested in continuing to use the app, but due to the error in this topic, I'm currently unable to. Thank you for taking the time to reply. I gave it a star because I believe the project deserves recognition.

**Comment by kobrastile** [comment]
Thanks for all the work on this!
I havs the same issue.

Pixel 8 pro grapheneos 2024091900
Switching between stock keyboard and openboard makes no difference.
I just uninstalled fossify messages set stock messages app to default, and it didn't have drafts. Somehow, for some reason, the drafts came back after reinstalling fossify messages though.

**Comment by Vennesaa** [comment]
@kobrastile look at above: [@ZicPL answer](https://github.com/FossifyOrg/Messages/issues/13#issuecomment-2119467732)

**Comment by Hraefin** [comment]
Same problem. 
OnePlus 7 pro  with Android 11. 
Love the app. Weird bug.

**Comment by naveensingh** [comment]
Should be fixed in the next update, we'll reopen otherwise.

**Comment by Hraefin** [comment]
Sadly, still the same issue. Type a message and back out without sending then go back in and send. Looks fine. Back out and your see the same message forever as a draft. If it's a long message, really painful to delete over and over.

**Comment by Aga-C** [comment]
@Hraefin 
1. If you do the same steps as in the original bug report (without sending, only removing), do you also have this problem?
2. Does it happen only with long messages, or with short ones too?
3. Do you have checked `Send long messages as MMS` in Settings?

@ZicPL I see you've added a thumb up. Do you also have this problem? If so, can you also reply to the questions above?

**Comment by kobrastile** [comment]
Unfortunately, the issue has persisted for me as well. I did a fresh install of Fossify Messages. I then proceeded to kill it and blow out the cache and storage for the app to re-import and the draft I just made re-appeared.

1. If you do the same steps as in the original bug report (without sending, only removing), do you also have this problem?
I do still have the problem.

2. Does it happen only with long messages, or with short ones too?
Both

3. Do you have checked Send long messages as MMS in Settings?
Checked and unchecked.

I'm currently using QUIK and between that and the default AOSP Messages app installed on GrapheneOS, Fossify Messages is the only one that sees the draft.

**Comment by naveensingh** [comment]
I can only reproduce this by creating and deleting hundreds of drafts programmatically in quick succession. I'll check it again.

**Comment by naveensingh** [comment]
It seems both AOSP and QUIK messaging apps save drafts to their internal databases:

 - https://cs.android.com/android/platform/superproject/+/android14-qpr3-release:packages/apps/Messaging/src/com/android/messaging/datamodel/action/WriteDraftMessageAction.java;l=75
 - https://github.com/octoshrimpy/quik/blob/1ba78533036634a40ac65ae8c95abebf3950f921/data/src/main/java/com/moez/QKSMS/repository/ConversationRepositoryImpl.kt#L301-L313

That's why the drafts created using Fossify Messages don't show up in other apps.

**Comment by naveensingh** [comment]
As I cannot 'organically' reproduce this bug on any phone, here are some test APKs:

- [messages-foss-fix-1.apk.zip](https://github.com/user-attachments/files/18293886/messages-foss-fix-1.apk.zip)
- [messages-foss-fix-2.apk.zip](https://github.com/user-attachments/files/18293887/messages-foss-fix-2.apk.zip)
- [messages-foss-fix-3.apk.zip](https://github.com/user-attachments/files/18293892/messages-foss-fix-3.apk.zip)

You just have to remove the `.zip` extension before installing. These are signed release builds.

**Comment by naveensingh** [comment]
Here's another:

- [messages-foss-fix-4.apk.zip](https://github.com/user-attachments/files/18293933/messages-foss-fix-4.apk.zip)

This uses an internal db for drafts so please DO NOT install this unless you are okay with reinstalling the official version.

**Comment by Hraefin** [comment]
Fix #2 worked perfectly for me.  1 did not.  After #2, I installed #3 and that seemed to work fine as well.  So maybe more testing needed with reinstalling vanilla version and then 3 to see if it works.  I can do that if you like.

**Comment by Hraefin** [comment]
Ok, I reinstalled the release and then fix #3 and that works perfectly as well.

**Comment by naveensingh** [comment]
Great, thanks for testing!
