### ISSUE TITLE
Opening a conversation changes its time/date

### ISSUE THREAD

**Issue by antodc** [FossifyOrg/Messages#274]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Messages/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Messages/issues) or [closed](https://github.com/FossifyOrg/Messages/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Messages/discussions) or [closed](https://github.com/FossifyOrg/Messages/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Messages/blob/master/CONTRIBUTING.md).

### Affected app version

1.1.1

### Affected Android/Custom ROM version

Android 11

### Affected device model

Oscal C60

### How did you install the app?

GitHub releases

### Steps to reproduce the bug

1. Open a conversation
2. Close the conversation

### Expected behavior

Nothing happens

### Actual behavior

The time/date of the converdation shown in the conversation list is changed to the current time/date

### Screenshots/Screen recordings

Before obtaining this strange behaviour I created and deleted a draft message in one of the conversations. Not sure whether this may have caused this issue.

Additional information. I reinstalled version 1.1.0. For all conversations with changed time it shows "draft", but when opening the conversation there is no draft there. After closing the converdation the "draft" word disapears. So, indeed the issue reported here may be related to having created/deleted a draft message in one of the convetsations.

**Comment by CapoFantasma97** [comment]
Same, this is absurd. Open a message, go back to the main menu and magically the entire conversation shows as if it was just updated and is sent to the top of the list. Makes the app quite unusable, when you can't distinguish anymore betweeen conversations from months ago and ones you received today.

**Comment by naveensingh** [comment]
Should be fixed in https://github.com/FossifyOrg/Messages/releases/tag/1.1.2

**Comment by tswistak** [comment]
@naveensingh Is it proper behavior, that this fix doesn't fix the already corrupted dates? I entered the old conversation in 1.1.1, and now I still have it on top of my conversations list.

**Comment by naveensingh** [comment]
I guess I'll do another release for that.

**Comment by naveensingh** [comment]
@tswistak please try https://github.com/FossifyOrg/Messages/releases/tag/1.1.3

**Comment by tswistak** [comment]
@naveensingh It works 🚀. A few seconds after startup, all dates have been reverted.

**Comment by antodc** [comment]
Yes!!! Thank you @naveensingh !!

**Comment by naveensingh** [comment]
I'm glad it worked, sorry for the trouble and thank you for reporting!

In the future, we'll have automated tests to catch bugs like this.
